version: '3.4'

services:
  ui:
    image: ui
    container_name: ui-prod
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    environment:
      NODE_ENV: production
    ports:
      - 8080:80
